<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BeneficiarySeeder extends Seeder
{
    public function run()
    {
        DB::table('beneficiaries')->insert([
            [
                'nik' => '3201010101010001',
                'name' => 'Beneficiary A',
                'birth_place' => 'A\'s Birth Place',
                'birth_date' => '2010-01-01',
                'gender' => 'P',
                'neighborhood_unit' => '01/04',
                'father' => 'Father A',
                'mother' => 'Mother A',
                'education_level' => 'SD',
                'school_grade' => '1',
                'shirt_size' => 'M',
                'shoe_size' => '36',
                'status' => 'Yatim',
                'phone_number' => '087789892020',
                'death_certificate_number' => 'AK/29/TOT/KENT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201020202020002',
                'name' => 'Beneficiary B',
                'birth_place' => 'B\'s Birth Place',
                'birth_date' => '2011-05-01',
                'gender' => 'L',
                'neighborhood_unit' => '01/04',
                'father' => 'Father B',
                'mother' => 'Mother B',
                'education_level' => 'SD',
                'school_grade' => '2',
                'shirt_size' => 'L',
                'shoe_size' => '37',
                'status' => 'Yatim',
                'phone_number' => '087789892020',
                'death_certificate_number' => 'AK/29/TOT/KENT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201030303030003',
                'name' => 'Beneficiary C',
                'birth_place' => 'C\'s Birth Place',
                'birth_date' => '2012-10-01',
                'gender' => 'P',
                'neighborhood_unit' => '02/04',
                'father' => 'Father C',
                'mother' => 'Mother C',
                'education_level' => 'SMP',
                'school_grade' => '3',
                'shirt_size' => 'M',
                'shoe_size' => '38',
                'status' => 'Yatim',
                'phone_number' => '087789892020',
                'death_certificate_number' => 'AK/29/TOT/KENT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201040404040004',
                'name' => 'Beneficiary D',
                'birth_place' => 'D\'s Birth Place',
                'birth_date' => '2013-03-01',
                'gender' => 'L',
                'neighborhood_unit' => '02/04',
                'father' => 'Father D',
                'mother' => 'Mother D',
                'education_level' => 'SD',
                'school_grade' => '4',
                'shirt_size' => 'S',
                'shoe_size' => '35',
                'status' => 'Yatim',
                'phone_number' => '087789892020',
                'death_certificate_number' => 'AK/29/TOT/KENT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nik' => '3201101010100010',
                'name' => 'Beneficiary E',
                'birth_place' => 'E\'s Birth Place',
                'birth_date' => '2014-07-01',
                'gender' => 'P',
                'neighborhood_unit' => '01/03',
                'father' => 'Father E',
                'mother' => 'Mother E',
                'education_level' => 'TK',
                'school_grade' => '1',
                'shirt_size' => 'XS',
                'shoe_size' => '34',
                'status' => 'Yatim',
                'phone_number' => '087789892020',
                'death_certificate_number' => 'AK/29/TOT/KENT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
